spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://costudy-db-container:3306/costudy?serverTimezone=UTC&characterEncoding=UTF-8
    password: costudy
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'false'
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: '50002'
